export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";

export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";

export const USER_UPDATE_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";

export const LOAD_USER_COUNTRY = "LOAD_USER_COUNTRY";
export const UPDATE_USER_COUNTRY = "UPDATE_USER_COUNTRY";

export const SEARCH_FILTER = "SEARCH_FILTER";

export const LANGUAGE = "LANGUAGE";

export const USER_LOGOUT =  "USER_LOGOUT"