require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'bellefu_app_v1' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])


  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-twilio-video-webrtc', :path => '../node_modules/react-native-twilio-video-webrtc'

  target 'bellefu_app_v1Tests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'bellefu_app_v1-tvOS' do
  # Pods for bellefu_app_v1-tvOS

  target 'bellefu_app_v1-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
